# =============================================================================
# add_preferences.R  -  time and risk preference scores from the staircases
# =============================================================================
# Deliberately NOT part of the cleaning pipeline. The score is a rank within the
# sample: standardising it means every respondent's number moves when the sample
# changes. Cleaning must give the same answer every time it runs, so this lives
# outside it and is run when an analysis needs it.
#
# Two ways to use it:
#
#   source("R/add_preferences.R")            # defines the functions, does nothing
#   dat <- add_preference_scores(dat)        # ... on whatever sample you analyse
#
#   Rscript R/add_preferences.R              # writes preferences.* next to the
#                                            # cleaned data, for all respondents
#
# Prefer the first when the analysis has a sample: standardising on the sample
# you actually estimate on is what the GPS convention means. The written file
# standardises over everyone who answered at least one question, which is the
# reasonable default but is only a default.
#
# =============================================================================
# WHAT THE STAIRCASE IS
# =============================================================================
# Q "Zeitpraeferenzen" and "Risikopraeferenzen" are the quantitative component of
# the Global Preference Survey (Falk, Becker, Dohmen, Enke, Huffman and Sunde,
# 2018, QJE, Section II.B). Each is up to five binary choices, and each choice
# sets the terms of the next one so that the sequence closes in on the point
# where the respondent is indifferent:
#
#   TIME  100 EUR today  vs  X EUR in 12 months.   Taking the money today raises
#         X for the next question, waiting lowers it. X starts at 154 and ends
#         somewhere between 103 and 215. Waiting is the patient answer, and it
#         is always option B.
#
#   RISK  a 50/50 lottery on 300 EUR  vs  a sure S EUR.   Taking the lottery
#         raises S, taking the sure payment lowers it. S starts at 160 and ends
#         somewhere between 10 and 310. The lottery is the risk-tolerant answer,
#         and it is always option A.
#
# Five choices sort each respondent into one of 32 ordered cells - what the
# paper calls the 32 possible ordered outcomes.
#
# =============================================================================
# WHAT THIS IS AND IS NOT
# =============================================================================
# The published GPS measure combines this staircase with a single Likert
# self-assessment ("how willing are you to..."), weighted 71/29 for patience and
# 47/53 for risk taking (Table I of the paper). This questionnaire has no such
# item, so what is built here is the staircase component alone. It is a valid
# ordering of respondents; it is not the validated GPS composite, and it should
# not be compared to published GPS country means.
#
# =============================================================================
# FROM PATH TO NUMBER
# =============================================================================
# The five answers are read as a binary number, earliest choice most
# significant, with the patient / risk-tolerant answer counting as 1. That
# number is the cell, and it runs from least to most patient / risk tolerant -
# which is a property of the staircase, not an assumption: at every level the
# amount offered rises monotonically with the number of impatient (resp.
# risk-tolerant) answers so far, and the pipeline's self-test checks it.
#
# `*_score` is the midpoint of the cell, expressed as a fraction of (0, 1):
# 0 = most impatient / most risk averse, 1 = most patient / most risk tolerant.
#
# NOT EVERYONE GETS FIVE LEVELS. Two questions were never generated by
# LimeSurvey: a respondent whose first three time answers were A, B, B has no
# fifth question at all, and stops after four (183 respondents here). Others
# broke off mid-staircase. A shorter path gives a wider cell, and the midpoint
# of that wider cell is exactly the average of the two narrower cells it
# contains - so a truncated respondent is placed in the middle of the range they
# were on their way into, without bias in either direction. `*_levels` records
# the depth so shallow paths can be dropped: at depth 1 the score is only a
# coin-flip between 0.25 and 0.75.
# =============================================================================

if (!file.exists("config.R"))
  stop("Run this from the project root (the folder containing config.R).", call. = FALSE)

source("config.R")

# The direction that counts as 1, and how to recognise it. The staircase columns
# are two-level factors whose FIRST level is always option A and whose second is
# option B - the LimeSurvey syntax files declare them as levels=c("A","B") and
# 02_read_stack.R keeps that order. Nothing in the data says "A" any more,
# though: the labels are the amounts. So rather than trusting the order
# silently, `option_a` is a pattern that option A's label must match, and
# `check_staircase()` refuses to score anything that does not.
STAIRCASES <- list(
  tp   = list(prefix = "tp_",   high = "B", option_a = "heute",
              what = "patience (option B = wait for the larger later payment)"),
  risk = list(prefix = "risk_", high = "A", option_a = "^Verlosung",
              what = "risk tolerance (option A = take the 50/50 lottery)")
)

# --- the columns of one staircase --------------------------------------------
# tp_5bbba -> level 5, path BBB A ... no: level 5, reached after answering BBBA.
# The letters after the digit are the answers given so far, so their number is
# the level minus one.
staircase_nodes <- function(data, prefix) {
  cols <- str_subset(names(data), str_c("^", prefix, "[0-9]"))
  tibble(col   = cols,
         level = as.integer(str_sub(str_remove(cols, str_c("^", prefix)), 1, 1)),
         path  = str_to_upper(str_sub(str_remove(cols, str_c("^", prefix)), 2)))
}

# --- refuse to guess ----------------------------------------------------------
# Everything downstream rests on "first level = option A". If a future export
# ever reverses the order, both scores would silently invert and nothing would
# look wrong - so it is checked rather than assumed.
check_staircase <- function(data, s) {
  nodes <- staircase_nodes(data, s$prefix)
  if (!nrow(nodes))
    stop("No ", s$prefix, "* columns in `data`. The staircase answers live in ",
         "survey_main, not in vignettes_long.\n",
         "For vignette-level work, score survey_main first and join the result:\n",
         '  prefs <- add_preference_scores(survey_main)\n',
         '  vl <- left_join(vl, select(prefs, resp_uid, ends_with(c("_score", "_z"))), ',
         'by = "resp_uid")', call. = FALSE)

  for (v in nodes$col) {
    lv <- levels(data[[v]])
    if (length(lv) != 2)
      stop(v, " has ", length(lv), " levels, expected 2 (the two options).",
           call. = FALSE)
    if (!str_detect(lv[1], s$option_a))
      stop("The first level of ", v, ' is "', lv[1], '", which does not look like ',
           "option A (expected to match /", s$option_a, "/).\n",
           "The score depends on option A coming first - refusing to guess.",
           call. = FALSE)
  }
  nodes
}

# --- walk one staircase -------------------------------------------------------
# Follows each respondent down the branch their own answers put them on. A
# respondent who skipped a level stops there, even if there are answers further
# down: without the intermediate answer the path is unknown, and those stray
# answers are counted and returned rather than quietly used.
walk_staircase <- function(data, s) {
  nodes <- check_staircase(data, s)
  n <- nrow(data)
  path <- rep("", n); cell <- rep(0L, n); depth <- rep(0L, n)
  active <- rep(TRUE, n)

  for (k in sort(unique(nodes$level))) {
    for (p in unique(path[active])) {
      v <- nodes$col[nodes$level == k & nodes$path == p]
      if (!length(v)) next          # this branch has no question at this level
      rows <- active & path == p
      vals <- data[[v]][rows]
      answered <- !is.na(vals)
      if (!any(answered)) next

      idx    <- which(rows)[answered]
      letter <- if_else(as.integer(vals[answered]) == 1L, "A", "B")
      path[idx]  <- str_c(path[idx], letter)
      cell[idx]  <- cell[idx] * 2L + as.integer(letter == s$high)
      depth[idx] <- k
    }
    active <- depth == k
  }

  # answers sitting on a branch the respondent never entered - LimeSurvey lets
  # people go back and change an earlier answer, which leaves the old branch
  # filled in. Counted so it shows up in the report instead of vanishing.
  stray <- integer(n)
  for (i in seq_len(nrow(nodes))) {
    on <- depth >= nodes$level[i] &
      str_sub(path, 1, str_length(nodes$path[i])) == nodes$path[i]
    stray <- stray + as.integer(!is.na(data[[nodes$col[i]]]) & !on)
  }

  # deepest level this respondent's branch could have reached, so a path cut
  # short by the questionnaire is distinguishable from one cut short by the
  # respondent
  reachable <- vapply(path, function(p) {
    d <- 0L
    for (k in sort(unique(nodes$level)))
      if (any(nodes$level == k & nodes$path == str_sub(p, 1, k - 1))) d <- k
    d
  }, integer(1), USE.NAMES = FALSE)

  tibble(path = path, cell = cell, depth = depth, max_depth = reachable,
         stray = stray,
         score = if_else(depth == 0L, NA_real_, (cell + 0.5) / 2^depth))
}

# =============================================================================
# add_preference_scores()
# =============================================================================
# Adds, for each of the two staircases:
#   <s>_score      midpoint of the cell, in (0, 1). Not sample-dependent.
#   <s>_z          the same, z-standardised over `standardise_on`.
#   <s>_cell       the cell itself, 0 .. 2^depth - 1
#   <s>_levels     how many of the five choices were answered
#   <s>_complete   TRUE if the respondent went as deep as their branch allows
#
# `standardise_on` is a logical vector over the rows of `data`, or NULL for
# "everyone who answered at least one question". Pass the analysis sample here.
#
# `min_levels` blanks the score for respondents who answered fewer than that
# many questions. The default keeps everybody - a two-level path is a real, if
# coarse, ranking - but set it to 4 or 5 if the coarse cells bother you.
add_preference_scores <- function(data, standardise_on = NULL, min_levels = 1L,
                                  quiet = FALSE) {
  stopifnot(is.data.frame(data))
  if (!is.null(standardise_on)) {
    if (length(standardise_on) != nrow(data))
      stop("`standardise_on` must have one entry per row of `data` (",
           nrow(data), ").", call. = FALSE)
    standardise_on <- !is.na(standardise_on) & standardise_on
  }

  # One row per respondent. survey_main is already one row each; vignettes_long
  # is not, so the score is worked out once and joined back on.
  if (!"resp_uid" %in% names(data))
    stop("`data` has no resp_uid column.", call. = FALSE)
  first <- !duplicated(data$resp_uid)

  for (nm in names(STAIRCASES)) {
    s <- STAIRCASES[[nm]]
    r <- walk_staircase(data[first, , drop = FALSE], s)

    score <- if_else(r$depth >= min_levels, r$score, NA_real_)

    # z is computed on the chosen sample and then applied to everyone, so a
    # respondent outside the sample still gets a comparable number rather than
    # NA - and the sample is what defines the scale, not who ends up with a
    # value.
    keep <- if (is.null(standardise_on)) rep(TRUE, length(score)) else standardise_on[first]
    m  <- mean(score[keep], na.rm = TRUE)
    sd <- stats::sd(score[keep], na.rm = TRUE)
    if (!is.finite(sd) || sd == 0)
      stop("Cannot standardise ", nm, ": the standardisation sample has ",
           sum(!is.na(score[keep])), " scored respondent(s).", call. = FALSE)

    per_resp <- tibble(resp_uid = data$resp_uid[first])
    per_resp[[str_c(nm, "_score")]]    <- score
    per_resp[[str_c(nm, "_z")]]        <- (score - m) / sd
    per_resp[[str_c(nm, "_cell")]]     <- if_else(r$depth == 0L, NA_integer_, r$cell)
    per_resp[[str_c(nm, "_levels")]]   <- r$depth
    per_resp[[str_c(nm, "_complete")]] <- r$depth > 0L & r$depth == r$max_depth

    data <- left_join(data, per_resp, by = "resp_uid")

    if (!quiet)
      message(nm, ": ", sum(!is.na(score)), " of ", nrow(per_resp), " respondents scored, ",
              sum(r$depth > 0 & r$depth < r$max_depth), " broke off mid-staircase, ",
              sum(r$stray > 0), " with answers on an abandoned branch",
              "  [z over ", sum(keep & !is.na(score)), "]")
  }
  data
}

# =============================================================================
# standalone run
# =============================================================================
# Writes a side table keyed on resp_uid rather than adding columns to
# survey_main: which columns survey_main has should depend only on
# run_cleaning.R, never on which other scripts happen to have been run.
# Join it the same way as the vignettes, on resp_uid.
if (!interactive() && sys.nframe() == 0L) {

  main_file <- file.path(CLEAN_DATA_DIR, "survey_main.rds")
  if (!file.exists(main_file))
    stop(main_file, " does not exist - run R/run_cleaning.R first.", call. = FALSE)

  survey_main <- readRDS(main_file)
  scored <- add_preference_scores(survey_main)

  preferences <- scored |>
    select(resp_uid, wave, is_complete,
           starts_with("tp_"), starts_with("risk_"),
           -matches("^(tp|risk)_[0-9]"))          # the raw answers stay in survey_main

  saveRDS(preferences,   file.path(CLEAN_DATA_DIR, "preferences.rds"))
  write_csv(preferences, file.path(CLEAN_DATA_DIR, "preferences.csv"), na = "")

  # A short report, next to the cleaning diagnostics. Everything here is about
  # the sample, not about individuals, so it can live in Dropbox.
  depth_tab <- bind_rows(
    count(preferences, measure = "time", levels = tp_levels),
    count(preferences, measure = "risk", levels = risk_levels))

  summary_tab <- tibble(
    measure = c("time (patience)", "risk tolerance"),
    scored  = c(sum(!is.na(preferences$tp_score)), sum(!is.na(preferences$risk_score))),
    reached_full_depth = c(sum(preferences$tp_complete), sum(preferences$risk_complete)),
    mean_raw = c(mean(preferences$tp_score, na.rm = TRUE),
                 mean(preferences$risk_score, na.rm = TRUE)),
    sd_raw   = c(stats::sd(preferences$tp_score, na.rm = TRUE),
                 stats::sd(preferences$risk_score, na.rm = TRUE)),
    distinct_cells = c(n_distinct(na.omit(preferences$tp_cell)),
                       n_distinct(na.omit(preferences$risk_cell))))

  notes <- tribble(
    ~item, ~note,
    "What this is",
    str_c("The staircase component of the GPS preference measures (Falk et al. 2018, ",
          "QJE). NOT the published GPS composite - this questionnaire has no Likert ",
          "self-assessment to combine with the staircase."),
    "*_score",
    "Midpoint of the respondent's cell, in (0, 1). 0 = most impatient / most risk averse.",
    "*_z",
    str_c("*_score standardised over everyone who answered at least one question. ",
          "This is a DEFAULT, not a property of the data: re-standardise on your own ",
          "analysis sample with add_preference_scores(dat, standardise_on = ...)."),
    "*_levels",
    "How many of the five choices were answered. At depth 1 the score is only 0.25 or 0.75.",
    "*_complete",
    str_c("TRUE if the respondent went as deep as their branch allows. The time ",
          "staircase has no fifth question on the A-B-B branch - LimeSurvey never ",
          "generated Time5ABBA/ABBB - so those respondents are complete at four."),
    "Join",
    "On resp_uid, the same key as vignettes_long."
  )

  write_xlsx(list(notes = notes, summary = summary_tab, depth = depth_tab),
             file.path(REPORT_DIR, "preferences_report.xlsx"))

  message("\npreferences.rds / .csv -> ", normalizePath(CLEAN_DATA_DIR))
  message("preferences_report.xlsx -> ", normalizePath(REPORT_DIR))
}
